elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
  restart: unless-stopped
  ports: ["9200-9300:9200-9300"]
  volumes: [
    "/etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml",
    "/etc/elasticsearch/logging.yml:/usr/share/elasticsearch/config/logging.yml"
  ]
  ulimits:
    memlock:
      soft: -1
      hard: -1

elasticsearch-exporter:
  image: justwatch/elasticsearch_exporter:1.0.2
  ports: ["9108:9108"]
  command: ["-es.uri=http://172.17.0.1:9200"]
  restart: unless-stopped
