http.port: 9200
http.publish_port: 9200
http.bind_host: 0.0.0.0
http.publish_host: {{ privateIP }}

transport.tcp.port: 9300
transport.publish_port: 9300
transport.bind_host: 0.0.0.0
transport.publish_host: {{ privateIP }}

path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

node.name: {{ hostname }}
cluster.name: {{ elasticsearch_cluster_name }}

discovery.zen.minimum_master_nodes: {{ elasticsearch_minimum_master_nodes }}
discovery.zen.ping.unicast.hosts: {{ elasticsearch_hosts }}

# searchguard:
#   ssl:
#     transport:
#       pemkey_filepath:
#       pemkey_password:
#       pemcert_filepath:
#       pemtrustedcas_filepath:

#   http:
#     pemkey_filepath:
#     pemkey_password:
#     pemcert_filepath:
#     pemtrustedcas_filepath:

#   nodes_dn:
#     - 'CN=node.other.com,OU=SSL,O=Test,L=Test,C=DE'
#     - 'CN=*.example.com,OU=SSL,O=Test,L=Test,C=DE'
#     - 'CN=elk-devcluster*'
#     - '/CN=.*regex/'
