prometheus:
  image: prom/prometheus:v2.0.0
  command: --config.file=/etc/prometheus/prometheus.yml --web.external-url=https://prometheus.livingdocs.io --web.route-prefix=/ --storage.tsdb.path=/data --storage.tsdb.retention=6m --web.enable-lifecycle
  ports: ["9090:9090"]
  volumes: ['/etc/prometheus:/etc/prometheus:ro', '/data/prometheus:/data']
  restart: unless-stopped
