prometheus:
  image: prom/prometheus:v2.3.1
  command: --config.file=/opt/prometheus/prometheus.yml --web.external-url=https://{{ cluster_domain_prometheus }} --web.route-prefix=/ --storage.tsdb.path=/data --storage.tsdb.retention=120d --web.enable-lifecycle
  ports: ['9090:9090']
  volumes: ['/opt/prometheus:/opt/prometheus:ro', '/data/prometheus:/data']
  restart: unless-stopped
