filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

- type: log
  paths:
   - '/var/lib/system-docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/system-docker.sock"

output.elasticsearch:
  hosts: {{ elasticsearch_hosts }}
