---
- name: Waiting for Cluster Health "green"
  action: shell warn=False curl -s -m 2 localhost:9200/_cluster/health?wait_for_status=green
  register: clusterstate
  until: clusterstate.stdout.find("green") != -1
  retries: 20
  delay: 3
  tags: [healthcheck]

- name: Echo docker container status
  shell: '{% raw %}docker ps -a --format "{{.ID}}: {{.Names}} - {{.Status}}"{% endraw %}'
  register: dockerstate
  tags: [healthcheck]

- debug: msg="{{ clusterstate.stdout }}"
  tags: [healthcheck]

- debug: msg="{{ dockerstate.stdout }}"
  tags: [healthcheck]
