node-exporter:
  restart: always
  image: prom/node-exporter:v0.17.0-rc.0
  net: host
  pid: host
  ports: ['9100:9100']
  command: --path.rootfs /rootfs --collector.filesystem.ignored-mount-points '^/(sys|dev|var|run)($$|/)'
  volumes: ['/:/rootfs:ro,rslave']
  labels: ['io.rancher.os.after=network', 'io.rancher.os.scope=system']

# cadvisor needs access to the console docker socket,
# therefore we can't run it on the system docker
# maybe we could even get rid of cadvisor if we
# don't need network and memory stats per container
cadvisor:
  restart: always
  image: google/cadvisor:v0.27.4
  ports: ['8080:8080']
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  labels: ['io.rancher.os.after=network']

coredns:
  restart: always
  image: coredns/coredns:1.1.4
  # We need to expose the container using --net=host
  # Because both subnets (rancher os and regular namespace) need to be able to contact
  # the dns server. The ip address we're using to contact it is `172.18.42.1`
  net: host
  ports: ['53:53', '53:53/udp', '9153:9153']
  command: -conf /opt/coredns/Corefile
  volumes: ['/opt/coredns:/opt/coredns']
  labels: ['io.rancher.os.after=network', 'io.rancher.os.scope=system']
