---
- name: Create ssh private and public keys
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create ssh key directory
    file: path="{{ lookup('env','PWD') }}/.ssh" state=directory

  - name: Generate SSH Private Key
    openssl_privatekey:
      path: "{{ lookup('env','PWD') }}/.ssh/id_rsa"

  - name: Generate SSH Public Key
    openssl_publickey:
      path: "{{ lookup('env','PWD') }}/.ssh/id_rsa.pub"
      privatekey_path: "{{ lookup('env','PWD') }}/.ssh/id_rsa"
      format: OpenSSH
