---
- name: Elasticsearch
  hosts: elasticsearch
  become: true
  gather_facts: true

  vars:
    elasticsearch_master_eligible_nodes: "{{ groups['elasticsearch'] | length }}"
    elasticsearch_cluster_name: logs
    elasticsearch_minimum_master_nodes: "{{ ((groups['elasticsearch'] | length) / 2) | int + 1 }}"
    elasticsearch_number_of_replicas: 0

  tasks:
  - name: Create Elasticsearch directory
    file: path=/etc/elasticsearch state=directory

  - set_fact:
      elasticsearch_hosts: "{{ hostvars | map_hostvars(groups, 'elasticsearch', 'ansible_default_ipv4.address') | to_json }}"

  - name: Generate elasticsearch.yml
    template:
      src: templates/elasticsearch/elasticsearch.yml
      dest: '/etc/elasticsearch/elasticsearch.yml'
      owner: root
      group: root
      mode: 0644

  - name: Generate logging.yml
    template:
      src: templates/elasticsearch/logging.yml
      dest: '/etc/elasticsearch/logging.yml'
      owner: root
      group: root
      mode: 0644

  - name: Generate docker-compose.yml
    template:
      src: templates/elasticsearch/docker-compose.yml
      dest: '/var/lib/rancher/conf/elasticsearch.yml'
      owner: root
      group: root
      mode: 0644

  - name: Deploy elasticsearch images on server
    raw: ros service enable /var/lib/rancher/conf/elasticsearch.yml

  - name: Start elasticsearch on server
    raw: ros service up elasticsearch

  - name: Start elasticsearch-exporter on server
    raw: ros service up elasticsearch-exporter

  - import_tasks: tasks/elasticsearch-cluster-health.yml
