---
- name: Elasticsearch
  hosts: es_ld_fra1
  become: true
  gather_facts: true

  vars:
    elasticsearch_master_eligible_nodes: "{{ groups['es_ld_fra1'] | length }}"
    elasticsearch_cluster_name: es_ld_fra1
    elasticsearch_minimum_master_nodes: "{{ ((groups['es_ld_fra1'] | length) / 2) | int + 1 }}"
    elasticsearch_number_of_replicas: 0

  tasks:
  - name: Create Elasticsearch directory
    file: path=/opt/elasticsearch state=directory

  - set_fact:
      elasticsearch_hosts: "{{ hostvars | map_hostvars(groups, 'es_ld_fra1', 'privateIP') | to_json }}"

  - name: Generate elasticsearch.yml
    template:
      src: templates/elasticsearch/elasticsearch.yml
      dest: '/opt/elasticsearch/elasticsearch.yml'
      owner: root
      group: root
      mode: 0644

  - name: Generate logging.yml
    template:
      src: templates/elasticsearch/logging.yml
      dest: '/opt/elasticsearch/logging.yml'
      owner: root
      group: root
      mode: 0644

  - name: Generate docker-compose.yml
    template:
      src: templates/elasticsearch/docker-compose.yml
      dest: '/var/lib/rancher/conf/elasticsearch.yml'
      owner: root
      group: root
      mode: 0644

  - name: Deploy elasticsearch images on server
    raw: ros service enable /var/lib/rancher/conf/elasticsearch.yml

  - name: Destroy the old elasticsearch container
    raw: (docker stop elasticsearch && docker rm elasticsearch) || docker rm -f elasticsearch
    ignore_errors: yes

  - name: Start elasticsearch on server
    raw: ros service up elasticsearch

  - name: Start elasticsearch-exporter on server
    raw: ros service up elasticsearch-exporter

  - import_tasks: tasks/elasticsearch-cluster-health.yml
