---
- name: Add a public key to all nodes
  hosts: all
  become: true
  gather_facts: false
  vars:
    public_key_openssh_file: "{{ lookup('env','PWD') }}/.ssh/id_rsa.pub"
    public_key_openssh: "{{ lookup('file', public_key_openssh_file) }}"

  tasks:
  - name: Register Custom Public Key on rancherOS node
    raw: |
      printf "ssh_authorized_keys:\n$(ros config get ssh_authorized_keys)" >> keys.yml
      if grep -q "{{ public_key_openssh }}" keys.yml
      then
          sed -i "s/^$2.*$/$3/" $1
          echo "- {{ public_key_openssh }}" >> keys.yml
          ros config merge -i keys.yml
          rm keys.yml
      fi
    register: output
    changed_when: output.stdout != ""

  - name: Add Custom Public Key to RancherOS console
    authorized_key:
      user: "{{ sshUser }}"
      key: "{{ public_key_openssh }}"
