---
- name: Monitoring Frontends
  hosts: monitoring
  become: true
  gather_facts: true
  vars:
    prometheus_ip: "{{ hostvars | map_hostvars(groups, 'prometheus', 'privateIP') | first }}"
    prometheus_port: 9090
    grafana_datasource_prometheus_url: "http://{{ prometheus_ip }}:{{ prometheus_port }}"

  tasks:
  - name: Create monitoring-frontends directory
    file: path=/opt/monitoring-frontends state=directory

  # Variables used for elasticsearch-hq
  - set_fact:
      elasticsearch_ansible_host: "{{ groups['elasticsearch'] | first }}"
    tags: [setup]

  - set_fact:
      elasticsearch_host: "http://{{ hostvars[elasticsearch_ansible_host].privateIP }}:9200"
      elasticsearch_hosts: "{{ hostvars | map_hostvars(groups, 'elasticsearch', 'privateIP') | to_json }}"
    tags: [setup]

  - name: Generate grafana.ini
    tags: [setup]
    template:
      src: templates/monitoring-frontends/{{ item }}
      dest: '/opt/monitoring-frontends/{{ item }}'
      owner: root
      group: root
      mode: 0644
    with_items: ["grafana.ini", "grafana-datasources.yml", "traefik.toml"]

  - name: Generate docker-compose.yml
    tags: [setup]
    template:
      src: templates/monitoring-frontends/docker-compose.yml
      dest: '/var/lib/rancher/conf/monitoring-frontends.yml'
      owner: root
      group: root
      mode: 0644

  - name: Deploy monitoring-frontends images on server
    raw: ros service enable /var/lib/rancher/conf/monitoring-frontends.yml

  - name: Start traefik on server
    raw: ros service up traefik

  - name: Start oauth-proxy on server
    raw: ros service up oauth-proxy

  - name: Start kibana on server
    raw: ros service up kibana

  - name: Start elasticsearch-hq on server
    raw: ros service up elasticsearch-hq

  - name: Start prometheus-proxy on server
    raw: ros service up prometheus-proxy
    tags: [prometheus]

  - name: Start grafana on server
    raw: ros service stop grafana && ros service up grafana
    tags: [grafana]

  - name: Start rancher-server on server
    raw: ros service stop rancher-server && ros service up rancher-server
    tags: [rancher]
