---
- name: Prometheus
  hosts: prometheus
  become: true
  gather_facts: true

  tasks:
  - name: Create prometheus directory
    file: path=/opt/prometheus state=directory

  - name: Generate prometheus.yml
    template:
      src: templates/prometheus/prometheus.yml
      dest: '/opt/prometheus/prometheus.yml'
      owner: root
      group: root
      mode: 0644
    tags: [config]

  - name: Waiting for prometheus to start up
    action: shell warn=False docker kill --signal=HUP prometheus
    tags: [never, config]

  # - name: show templating results
  #   debug: msg="{{ lookup('template', 'templates/prometheus/prometheus.yml') }}"

  - name: Generate docker-compose.yml
    template:
      src: templates/prometheus/docker-compose.yml
      dest: '/var/lib/rancher/conf/prometheus.yml'
      owner: root
      group: root
      mode: 0644

  - name: Create prometheus directory
    file:
      path: /data/prometheus
      state: directory
      mode: 0777

  - name: Deploy prometheus images on server
    raw: ros service enable /var/lib/rancher/conf/prometheus.yml

  - name: Destroy the old prometheus container
    raw: (docker stop prometheus && docker rm prometheus) || docker rm -f prometheus || echo 'no prometheus is running'
    ignore_errors: yes

  - name: Start prometheus on server
    raw: ros service up prometheus

  - name: Waiting for prometheus to start up
    action: shell warn=False curl -s --output /dev/null --write-out "%{http_code}" localhost:9090/metrics
    register: prometheusstate
    until: prometheusstate.stdout == "200"
    retries: 5
    delay: 1
    tags: [healthcheck]

  - name: Reload prometheus config
    action: shell warn=False curl -s -XPOST localhost:9090/-/reload
    tags: [healthcheck]
